// Generated by CoffeeScript 1.10.0
(function() {
  this.Ant = (function() {
    Ant.MOVEMENTS = [[0, -1], [-1, 0], [0, 1], [1, 0]];

    Ant.COLOR_CODES = {
      WHITE: '#FFFFFF',
      BLACK: '#000000',
      RED: '#FF0000',
      GREEN: '#00FF00',
      BLUE: '#0000FF',
      CYAN: '#00FFFF',
      YELLOW: '#FFFF00',
      MAGENTA: '#FF00FF'
    };

    function Ant(row, col, orientation, grid, rules, default_rules) {
      this.row = row;
      this.col = col;
      this.orientation = orientation;
      this.grid = grid;
      this.rules = rules;
      this.default_rules = default_rules != null ? default_rules : [];
    }

    Ant.prototype.turn = function(amount) {
      var results;
      this.orientation += amount;
      this.orientation %= Ant.MOVEMENTS.length;
      results = [];
      while (this.orientation < 0) {
        results.push(this.orientation += Ant.MOVEMENTS.length);
      }
      return results;
    };

    Ant.prototype.left = function() {
      return this.turn(-1);
    };

    Ant.prototype.right = function() {
      return this.turn(1);
    };

    Ant.prototype.get_color = function() {
      return this.grid[this.row][this.col];
    };

    Ant.prototype.set_color = function(color) {
      return this.grid[this.row][this.col] = color;
    };

    Ant.prototype.move = function() {
      var col_delta, ref, results, row_delta;
      ref = Ant.MOVEMENTS[this.orientation], row_delta = ref[0], col_delta = ref[1];
      this.row += row_delta;
      this.row %= this.grid.length;
      while (this.row < 0) {
        this.row += this.grid.length;
      }
      this.col += col_delta;
      this.col %= this.grid[0].length;
      results = [];
      while (this.col < 0) {
        results.push(this.col += this.grid[0].length);
      }
      return results;
    };

    Ant.prototype.step = function() {
      var current_color, i, len, ref, ref1, results, rule;
      current_color = this.get_color();
      ref1 = (ref = this.rules[current_color]) != null ? ref : this.default_rules;
      results = [];
      for (i = 0, len = ref1.length; i < len; i++) {
        rule = ref1[i];
        if (rule === "LEFT") {
          results.push(this.left());
        } else if (rule === "RIGHT") {
          results.push(this.right());
        } else if (rule === "MOVE") {
          results.push(this.move());
        } else if (rule in Ant.COLOR_CODES) {
          results.push(this.set_color(rule));
        } else {
          results.push(void 0);
        }
      }
      return results;
    };

    return Ant;

  })();

}).call(this);
